# Generated by Django 5.0 on 2024-03-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='name_ky',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='type_of_trainer',
            name='name_ky',
        ),
        migrations.RemoveField(
            model_name='type_of_trainer',
            name='name_ru',
        ),
    ]
