# Generated by Django 5.0 on 2024-03-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='desc_ky',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='desc_ru',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='title_ru',
        ),
    ]
