# Generated by Django 5.0 on 2024-03-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address_ky',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='holiday_work_time_ky',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='holiday_work_time_ru',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='work_time_ky',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='work_time_ru',
        ),
    ]
