# Generated by Django 5.0 on 2024-03-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='hours_week_ky',
        ),
        migrations.RemoveField(
            model_name='services',
            name='hours_week_ru',
        ),
        migrations.RemoveField(
            model_name='services',
            name='note_ky',
        ),
        migrations.RemoveField(
            model_name='services',
            name='note_ru',
        ),
        migrations.RemoveField(
            model_name='services',
            name='price_ky',
        ),
        migrations.RemoveField(
            model_name='services',
            name='price_ru',
        ),
        migrations.RemoveField(
            model_name='services',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='services',
            name='title_ru',
        ),
    ]
