# Generated by Django 5.0 on 2024-03-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='add_text_ky',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='add_text_ru',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='text_ky',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='text_ru',
        ),
    ]
