# Generated by Django 5.0 on 2024-03-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Abonements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonement',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='abonement',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='abonement',
            name='price_ky',
        ),
        migrations.RemoveField(
            model_name='abonement',
            name='price_ru',
        ),
        migrations.RemoveField(
            model_name='abonement',
            name='time_ky',
        ),
        migrations.RemoveField(
            model_name='abonement',
            name='time_ru',
        ),
        migrations.RemoveField(
            model_name='abonement',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='abonement',
            name='title_ru',
        ),
    ]
