# Generated by Django 5.0 on 2024-03-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainZone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainzone',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='trainzone',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='trainzone',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='trainzone',
            name='title_ru',
        ),
    ]
