# Generated by Django 5.0 on 2024-03-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer_ky',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_ru',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_ky',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_ru',
        ),
    ]
